### ISSUE TITLE
Failed to upload result file in CSV format

### ISSUE THREAD

**Issue by uasetum** [innogames/ltc#7]
Failed to upload results in CSV format by clicking 'Upload file with test results' button

'CSV file fields' values in 'Upload test result file' popup:
timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect

See attached data.txt for sample data to be uploaded
[data.txt](https://github.com/innogames/JMeter-Control-Center/files/1696599/data.txt)

See attached log.txt
[log.txt](https://github.com/innogames/JMeter-Control-Center/files/1696602/log.txt)

**Comment by v0devil** [comment]
This problem is that your CSV file has more columns than you have pointed in the "CSV file fields:" field.
There are 5 mandatory columns: _timestamp, response_time, url, responseCode, success_.
The timestamp must be always in the first column so we do not point it, everything else must be entered with the same order as in CSV file, all non-mandatory columns your can name as you want. 
So in your example, it will be:
response_time,url,responseCode,A,B,C,success,D,E,F,G,H,J,K,L
